ken:
    build: ./ken/
    volumes:
      - ken/ken:/var/www/html
    links:
      - mysql
      - redis
      - elasticsearch
      - dynamodb
    ports:
      - "80"
      - "443"
    restart: always
    command: /usr/bin/supervisord -n -c /etc/supervisor/supervisord.conf

mysql:
    build: ./mysql/
    expose:
      - "3306"
    restart: always

redis:
    build: ./redis/
    expose:
      - "6379"
    restart: always

elasticsearch:
    build: ./elasticsearch/
    expose:
      - "9200"
      - "9300"
    restart: always

dynamodb:
    build: ./dynamodb/
    expose:
      - "8001"
    restart: always

